name: 'Coins'

on: [push, pull_request]

jobs:
  cron-ui:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v2

      - name: Setup OpenJDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '16'
          cache: 'maven'

      - name: Execute tests
        env:
          TESTINGBOT_KEY: ${{ secrets.TESTINGBOT_KEY }}
          TESTINGBOT_SECRET: ${{ secrets.TESTINGBOT_SECRET }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: mvn clean -ntp test

      - name: Copying artifacts
        run: mkdir report && cp target/surefire-reports/*.xml report

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: report